name: Deploy to Production

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker images to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: muze
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build gRPC service from Dockerfile.grpc
        docker build -f Dockerfile.grpc -t $ECR_REGISTRY/$ECR_REPOSITORY:grpc-$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:grpc-$IMAGE_TAG
        
        # Build GraphQL service from Dockerfile.graphql
        docker build -f Dockerfile.graphql -t $ECR_REGISTRY/$ECR_REPOSITORY:graphql-$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:graphql-$IMAGE_TAG

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster muze-cluster --service muze-grpc-service --force-new-deployment
        aws ecs update-service --cluster muze-cluster --service muze-graphql-service --force-new-deployment
        echo "Deployment completed!"
